import '../styles/globals.css'
import 'tailwindcss/tailwind.css'
import Head from "next/head"
import { SessionProvider } from "next-auth/react"

function MyApp({ Component, pageProps: { session, ...pageProps } }) {
  return (
    <SessionProvider session={session} refetchInterval={5 * 60}>
       <Head>
        <title>NextJs GitHub Auth</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </SessionProvider>
    )
}

export default MyApp